Card
5-jigglypuff/pytrello2 pull request #16
Opened 2023-12-10 04:54 UTC by purplemoon-l

Updated Create Board API
Included all 5 functionalities of List
Included all 4 functionalities of Card
Removed Linter and formatting details

2023-12-10 05:31 UTC, vchrombie requested changes
Good work on the DCO, can you these comments?

2023-12-10 05:31 UTC, vchrombie commented on pytrello2/client.py
> +        return self._request("POST", endpoint, params=params)
Is this a required change?

2023-12-10 05:31 UTC, vchrombie commented on .gitignore
> +
This can be removed

2023-12-11 22:50 UTC, vchrombie commented
Please update the changes in the PR and description

2023-12-12 02:28 UTC, purplemoon-l commented on pytrello2/client.py
> +        return self._request("POST", endpoint, params=params)
Fixed it

2023-12-12 02:28 UTC, purplemoon-l commented on .gitignore
> +
Removed

2023-12-14 04:33 UTC, vchrombie commented on tests/test_models.py
> -# Test for board str method
Can you revert this?

2023-12-14 04:40 UTC, purplemoon-l commented on tests/test_models.py
> -# Test for board str method
Yes Done

2023-12-14 04:45 UTC, vchrombie approved these changes
LGTM! 🚀

2023-12-14 04:48 UTC, merged