Create List Methods
5-jigglypuff/pytrello2 pull request #17
Opened 2023-12-11 22:34 UTC by purplemoon-l

All 5 API(s)
1. Create List
2. Get List
3. Get All Cards in the list
4. Archive List
5. Update List

2023-12-13 23:52 UTC, vchrombie requested changes

2023-12-13 23:52 UTC, vchrombie commented on pytrello2/models/list.py
> +class Card:
```suggestion
class List
```

2023-12-13 23:52 UTC, vchrombie commented on pytrello2/models/list.py
> +            f"Card(id={self.id}, idBoard={self.idBoard}, name={self.name},"
```suggestion
            f"List(id={self.id}, idBoard={self.idBoard}, name={self.name},"
```

2023-12-14 00:24 UTC, vchrombie requested changes

2023-12-14 00:24 UTC, vchrombie commented on pytrello2/list.py
> +from .models.list import ListClass
```suggestion
from .models.list import List
```

2023-12-14 00:24 UTC, vchrombie commented on pytrello2/models/list.py
> +class ListClass:
```suggestion
class List:
```

2023-12-14 04:58 UTC, purplemoon-l commented on pytrello2/list.py
> +from .models.list import ListClass
Resolved

2023-12-14 05:04 UTC, vchrombie approved these changes
LGTM! 🚀

2023-12-14 05:04 UTC, merged